notifications:
  email: false
language: c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y -qq texlive pandoc texlive-latex-base texlive-latex-extra latexmk
  - git submodule init && git submodule update
script:
    make
before_deploy:
    test $TRAVIS_TEST_RESULT = 0
after_deploy:
    make clean
